# Generated by Django 3.2.15 on 2022-08-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tryindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='yahoo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('Open', models.FloatField(blank=True, null=True)),
                ('High', models.FloatField(blank=True, null=True)),
                ('Low', models.FloatField(blank=True, null=True)),
                ('Close', models.FloatField(blank=True, null=True)),
                ('Volume', models.FloatField(blank=True, null=True)),
                ('Dividends', models.FloatField(blank=True, null=True)),
                ('StockSplits', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='tryindex',
            index=models.Index(fields=['name', 'email'], name='App_tryinde_name_d43731_idx'),
        ),
    ]
