# Generated by Django 4.0.6 on 2023-03-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apptwo', '0002_company_phone_phoneuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='p_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apptwo.phoneuser'),
        ),
    ]
